### ISSUE TITLE
Should remove the github actions and binder bits from cookiecutter

### ISSUE THREAD

**Issue by cab938** [educational-technology-collective/etc_jupyterlab_telemetry#2]
Since I don't think we are planning to use these

**Comment by adpatter** [comment]
I removed the github actions, but I left in the binder stuff, as I thought someone might want to demo the extension at some point.  Please let me know if you are sure you want me to remove the binder stuff.

**Comment by adpatter** [comment]
I fixed the binder stuff in order to ensure that it loads the demo.
