### ISSUE TITLE
Clarify this

### ISSUE THREAD

**Issue by cab938** [educational-technology-collective/etc_jupyterlab_telemetry#5]
Since this is some internal coursera stuff can you add a comment here clarifying what the line does?

https://github.com/educational-technology-collective/etc_jupyterlab_telemetry/blob/5ae34e0579903d4c641acd8b9745a3241b4a1e7f/etc_jupyterlab_telemetry/handlers.py#L16

**Comment by adpatter** [comment]
This is done.  Thanks. @cab938
