### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by cab938** [educational-technology-collective/etc_jupyterlab_telemetry#8]
Can we set the telemetry extension logo to the lab light bulb icon?

![image](https://user-images.githubusercontent.com/1355641/124823180-e5205580-df3e-11eb-8170-8425232da02e.png)

**Comment by adpatter** [comment]
OK.  This should be all set.  And, I made the change in all the other JL repositories that I have created.  And, I will try to remember to do this when I set up new ones. @cab938
