### ISSUE TITLE
Telemetry throws 500 errors

### ISSUE THREAD

**Issue by cab938** [educational-technology-collective/etc_jupyterlab_telemetry#9]
I installed by cloning the repository, building the wheel, and installing it with pip. Seems like there is some cruft in the config.... somewhere?

![image](https://user-images.githubusercontent.com/1355641/124823507-4c3e0a00-df3f-11eb-89e9-e14f172e9d8c.png)

**Comment by adpatter** [comment]
@cab938 This will work now.  The AWS API Gateway Wrapper is configured to log to the S3 bucket named `telemetry-s3-aws-edtech-labs-si-umich-edu` and the path named `etc_telemetry`.  These settings are made when the Wrapper is instantiated.
